services:
  postgres:
    image: postgres:latest
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_network

  app:
    image: php:8.2-cli
    container_name: laravel_app
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - laravel_network
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    command: >
      bash -c "apt-get update && apt-get install -y libpq-dev &&
      docker-php-ext-install pdo pdo_pgsql &&
      php artisan serve --host=0.0.0.0 --port=8000"

  node:
    image: node:23
    container_name: laravel_node
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - laravel_network
    tty: true
    stdin_open: true
    # command: npm run dev

  vite:
    image: node:23
    container_name: laravel_vite
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - laravel_network
    ports:
      - "5173:5173"
    command: >
      bash -c "npm install &&
      npm run dev -- --host"

volumes:
  postgres_data:

networks:
  laravel_network:
    driver: bridge
